### ISSUE TITLE
TypeError: Cannot read property 'type' of null when using `for...of`

### ISSUE THREAD

**Issue by EvgenyOrekhov** [andykao1213/eslint-plugin-react-hook-form#11]
**Describe the bug**
ESLint exits with fatal error.

**To Reproduce**
1. The code you are going to lint.
```js
for (const element of array) {
  bar(element);
}
```
2. Your ESlint config
```json
{
  "parserOptions": {
    "ecmaVersion": "latest"
  },

  "plugins": ["react-hook-form"],

  "rules": {
    "react-hook-form/destructuring-formstate": "error"
  }
}

```

**Expected behavior**
No fatal error.

**Actual behavior**
```
Oops! Something went wrong! :(

ESLint: 8.6.0

TypeError: Cannot read property 'type' of null
Occurred while linting /example/example.js:1
Rule: "react-hook-form/destructuring-formstate"
    at check (/example/node_modules/eslint-plugin-react-hook-form/lib/rules/destructuring-formstate.js:45:19)
    at ruleErrorHandler (/example/node_modules/eslint/lib/linter/linter.js:1079:28)
    at /example/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/example/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/example/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/example/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/example/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
    at CodePathAnalyzer.enterNode (/example/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:795:23)
    at /example/node_modules/eslint/lib/linter/linter.js:1110:32
```

**Enviornment (please complete the following information):**
 - Eslint version: 8.6.0
 - Node version: 14.18.2
 - React-Hook-Form version: 0.2.1

**Additional context**

**Comment by andykao1213** [comment]
@EvgenyOrekhov Really appreciate the issue report.
The issue has been fixed in [v0.2.2](https://github.com/andykao1213/eslint-plugin-react-hook-form/releases/tag/v0.2.2). 
Please check if this version works for you.
Thank you 🙏🏼
